# Generated by Django 3.2.5 on 2022-09-27 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewee_firstname', models.CharField(default='', max_length=50)),
                ('interviewee_lastname', models.CharField(default='', max_length=50)),
                ('interviewee_email', models.CharField(default='', max_length=50)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('E', 'Empty'), ('T', 'Tentative'), ('C', 'Confirmed'), ('D', 'Declined')], default='E', max_length=1)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slot', to='accounts.interviewerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IntervieweeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('D', 'Declined'), ('T', 'Tentative')], default='T', max_length=1)),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewee_id', to='accounts.intervieweeprofile')),
                ('interviewer_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduling.interviewerschedule')),
            ],
        ),
    ]
