# Generated by Django 3.2.5 on 2022-09-28 03:41

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_interviewee', models.BooleanField(default=False)),
                ('is_interviewer', models.BooleanField(default=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=10)),
                ('country_code', models.PositiveSmallIntegerField(default=91)),
                ('user_timezone', models.CharField(choices=[('Asia/Kolkata', 'Asia/Kolkata [IST] [GMT + 05:30]'), ('UTC', 'UTC, [GMT + 00:00]')], default='Asia/Kolkata', max_length=32)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IntervieweeProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('tentative_field', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('about_me', models.TextField(default='Empty', max_length=200)),
                ('education_details', models.TextField(default='Empty', max_length=100)),
                ('employment_details', models.TextField(default='Empty', max_length=100)),
                ('mother_tongue', models.CharField(blank=True, max_length=20)),
                ('taken_ielts', models.BooleanField(default=False)),
                ('best_ielts_score', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('training_exp', models.CharField(choices=[('< 1yr', 'Less than 1 Year'), ('1 - 2yr', '1 to 2 Years'), ('2 - 3yr', '2 to 3 Years'), ('3 - 4yr', '3 to 4 Years'), ('4 - 5yr', '4 to 5 Years'), ('5+ yr', 'More than 5 Years')], default='< 1yr', max_length=15)),
                ('linkedin_profile', models.URLField(blank=True, max_length=60)),
                ('twitter_profile', models.URLField(blank=True, max_length=60)),
                ('facebook_profile', models.URLField(blank=True, max_length=60)),
                ('website_profile', models.URLField(blank=True, max_length=60)),
                ('insta_profile', models.URLField(blank=True, max_length=60)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('profile_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='default-avatar.jpg', force_format=None, keep_meta=True, quality=100, size=[200, 200], upload_to='profile_pics')),
            ],
        ),
    ]
